package br.ufg.es.sad.entity;
// Generated 11/06/2014 19:40:12 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Atividade generated by hbm2java
 */
@Entity
@Table(name = "atividade")
public class Atividade implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "grupo_id")
    private Grupo grupo;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "valor_id", nullable = false)
    private Valor valor;

    @Column(name = "nome", nullable = false, length = 45)
    private String nome;

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "atividade_resolucao", catalog = "phelipea_sad", joinColumns = {
        @JoinColumn(name = "atividade_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "resolucao_id", nullable = false, updatable = false)})
    private Set<Resolucao> resolucaos = new HashSet<Resolucao>(0);

    public Atividade() {
    }

    public Atividade(Valor valor, String nome) {
        this.valor = valor;
        this.nome = nome;
    }

    public Atividade(Grupo grupo, Valor valor, String nome, Set<Resolucao> resolucaos) {
        this.grupo = grupo;
        this.valor = valor;
        this.nome = nome;
        this.resolucaos = resolucaos;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Grupo getGrupo() {
        return this.grupo;
    }

    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }

    public Valor getValor() {
        return this.valor;
    }

    public void setValor(Valor valor) {
        this.valor = valor;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Set getResolucaos() {
        return this.resolucaos;
    }

    public void setResolucaos(Set resolucaos) {
        this.resolucaos = resolucaos;
    }

}
